server:
 port: 8080
 error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
   

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/creditapp_db
    username: creditapplication_user
    password: patika
    driver-class-name: org.postgresql.Driver
  
  jpa:
   show-sql: true
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   hibernate:
      ddl-auto: update
   properties:
    hibernate:
     format_sql: true

greenrent:
 app:
  jwtSecret: creditApp@123
  jwtExpirationMs: 86400000
      
      
logging:
 file:
  name: logs/creditApplication.log
 pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
 
 level:
   '[org.springframework.web]': INFO
   '[org.hibernate]': INFO
   '[com.greenrent]': DEBUG
   
info:
 application:
  name: 'creditApplicationSystem Backend App.'
  descprition: 'This is creditApplicationSystem Backend app dev by Abdulsamet Kaya'
  version: '@project.version@' 
 